// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Load [FirebaseOptions] from environment variables.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: dotenv.get("apiKey"),
        appId: dotenv.get("appId"),
        projectId: dotenv.get("projectId"),
        messagingSenderId: dotenv.get("messagingSenderId"),
        authDomain: dotenv.get("authDomain"),
        storageBucket: dotenv.get("storageBucket"),
        measurementId: dotenv.maybeGet("measurementId"),
      );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }
}
