// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALKwUaOYn7GjwMf0LmzxPllBB_8IYS-Bw',
    appId: '1:60616308654:web:e4750505b8209d019b7a3f',
    messagingSenderId: '60616308654',
    projectId: 'resourcepage-17330',
    authDomain: 'resourcepage-17330.firebaseapp.com',
    storageBucket: 'resourcepage-17330.appspot.com',
    measurementId: 'G-YF28M1CYND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrm38NBKodhK_zVjt0cgoAaMSQZ4xb1U',
    appId: '1:60616308654:android:b788a35e846b11f29b7a3f',
    messagingSenderId: '60616308654',
    projectId: 'resourcepage-17330',
    storageBucket: 'resourcepage-17330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWu_tvNQ-ZwVB9xmfcKAAU_eNFJHWcIDI',
    appId: '1:60616308654:ios:10dd733b1e7c72269b7a3f',
    messagingSenderId: '60616308654',
    projectId: 'resourcepage-17330',
    storageBucket: 'resourcepage-17330.appspot.com',
    iosClientId: '60616308654-3rk7i21prlap63r9tqf9npf0nup1p15k.apps.googleusercontent.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWu_tvNQ-ZwVB9xmfcKAAU_eNFJHWcIDI',
    appId: '1:60616308654:ios:10dd733b1e7c72269b7a3f',
    messagingSenderId: '60616308654',
    projectId: 'resourcepage-17330',
    storageBucket: 'resourcepage-17330.appspot.com',
    iosClientId: '60616308654-3rk7i21prlap63r9tqf9npf0nup1p15k.apps.googleusercontent.com',
    iosBundleId: 'com.example.webApp',
  );
}
